/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "bluez-iface.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.bluez.MediaEndpoint1 */

const GDBusArgInfo org_bluez_media_endpoint1_interface__select_configuration_method_in_args__capabilities_arg =
{
  -1,  /* ref count */
  (gchar *) "capabilities",
  (gchar *) "ay",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluez_media_endpoint1_interface__select_configuration_method_in_args[] =
{
  &org_bluez_media_endpoint1_interface__select_configuration_method_in_args__capabilities_arg,
  NULL,
};

const GDBusArgInfo org_bluez_media_endpoint1_interface__select_configuration_method_out_args__configuration_arg =
{
  -1,  /* ref count */
  (gchar *) "configuration",
  (gchar *) "ay",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluez_media_endpoint1_interface__select_configuration_method_out_args[] =
{
  &org_bluez_media_endpoint1_interface__select_configuration_method_out_args__configuration_arg,
  NULL,
};

const GDBusMethodInfo org_bluez_media_endpoint1_interface__select_configuration_method =
{
  -1,  /* ref count */
  (gchar *) "SelectConfiguration",
  (GDBusArgInfo **) org_bluez_media_endpoint1_interface__select_configuration_method_in_args,
  (GDBusArgInfo **) org_bluez_media_endpoint1_interface__select_configuration_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluez_media_endpoint1_interface__set_configuration_method_in_args__transport_arg =
{
  -1,  /* ref count */
  (gchar *) "transport",
  (gchar *) "o",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluez_media_endpoint1_interface__set_configuration_method_in_args__properties_arg =
{
  -1,  /* ref count */
  (gchar *) "properties",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluez_media_endpoint1_interface__set_configuration_method_in_args[] =
{
  &org_bluez_media_endpoint1_interface__set_configuration_method_in_args__transport_arg,
  &org_bluez_media_endpoint1_interface__set_configuration_method_in_args__properties_arg,
  NULL,
};

const GDBusMethodInfo org_bluez_media_endpoint1_interface__set_configuration_method =
{
  -1,  /* ref count */
  (gchar *) "SetConfiguration",
  (GDBusArgInfo **) org_bluez_media_endpoint1_interface__set_configuration_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluez_media_endpoint1_interface__clear_configuration_method_in_args__transport_arg =
{
  -1,  /* ref count */
  (gchar *) "transport",
  (gchar *) "o",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluez_media_endpoint1_interface__clear_configuration_method_in_args[] =
{
  &org_bluez_media_endpoint1_interface__clear_configuration_method_in_args__transport_arg,
  NULL,
};

const GDBusMethodInfo org_bluez_media_endpoint1_interface__clear_configuration_method =
{
  -1,  /* ref count */
  (gchar *) "ClearConfiguration",
  (GDBusArgInfo **) org_bluez_media_endpoint1_interface__clear_configuration_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo org_bluez_media_endpoint1_interface__release_method =
{
  -1,  /* ref count */
  (gchar *) "Release",
  NULL,  /* no in args */
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const org_bluez_media_endpoint1_interface_methods[] =
{
  &org_bluez_media_endpoint1_interface__select_configuration_method,
  &org_bluez_media_endpoint1_interface__set_configuration_method,
  &org_bluez_media_endpoint1_interface__clear_configuration_method,
  &org_bluez_media_endpoint1_interface__release_method,
  NULL,
};

const GDBusPropertyInfo org_bluez_media_endpoint1_interface__uuid_property =
{
  -1,  /* ref count */
  (gchar *) "UUID",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluez_media_endpoint1_interface__codec_property =
{
  -1,  /* ref count */
  (gchar *) "Codec",
  (gchar *) "y",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluez_media_endpoint1_interface__vendor_property =
{
  -1,  /* ref count */
  (gchar *) "Vendor",
  (gchar *) "u",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluez_media_endpoint1_interface__capabilities_property =
{
  -1,  /* ref count */
  (gchar *) "Capabilities",
  (gchar *) "ay",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluez_media_endpoint1_interface__device_property =
{
  -1,  /* ref count */
  (gchar *) "Device",
  (gchar *) "o",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluez_media_endpoint1_interface__delay_reporting_property =
{
  -1,  /* ref count */
  (gchar *) "DelayReporting",
  (gchar *) "b",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const org_bluez_media_endpoint1_interface_properties[] =
{
  &org_bluez_media_endpoint1_interface__uuid_property,
  &org_bluez_media_endpoint1_interface__codec_property,
  &org_bluez_media_endpoint1_interface__vendor_property,
  &org_bluez_media_endpoint1_interface__capabilities_property,
  &org_bluez_media_endpoint1_interface__device_property,
  &org_bluez_media_endpoint1_interface__delay_reporting_property,
  NULL,
};

const GDBusInterfaceInfo org_bluez_media_endpoint1_interface =
{
  -1,  /* ref count */
  (gchar *) "org.bluez.MediaEndpoint1",
  (GDBusMethodInfo **) org_bluez_media_endpoint1_interface_methods,
  NULL,  /* no signals */
  (GDBusPropertyInfo **) org_bluez_media_endpoint1_interface_properties,
  NULL,  /* no annotations */
};

/* ------------------------------------------------------------------------ */
/* Definitions for org.bluez.BatteryProvider1 */

const GDBusPropertyInfo org_bluez_battery_provider1_interface__device_property =
{
  -1,  /* ref count */
  (gchar *) "Device",
  (gchar *) "o",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluez_battery_provider1_interface__percentage_property =
{
  -1,  /* ref count */
  (gchar *) "Percentage",
  (gchar *) "y",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluez_battery_provider1_interface__source_property =
{
  -1,  /* ref count */
  (gchar *) "Source",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const org_bluez_battery_provider1_interface_properties[] =
{
  &org_bluez_battery_provider1_interface__device_property,
  &org_bluez_battery_provider1_interface__percentage_property,
  &org_bluez_battery_provider1_interface__source_property,
  NULL,
};

const GDBusInterfaceInfo org_bluez_battery_provider1_interface =
{
  -1,  /* ref count */
  (gchar *) "org.bluez.BatteryProvider1",
  NULL,  /* no methods */
  NULL,  /* no signals */
  (GDBusPropertyInfo **) org_bluez_battery_provider1_interface_properties,
  NULL,  /* no annotations */
};

/* ------------------------------------------------------------------------ */
/* Definitions for org.bluez.Profile1 */

const GDBusArgInfo org_bluez_profile1_interface__new_connection_method_in_args__device_arg =
{
  -1,  /* ref count */
  (gchar *) "device",
  (gchar *) "o",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluez_profile1_interface__new_connection_method_in_args__fd_arg =
{
  -1,  /* ref count */
  (gchar *) "fd",
  (gchar *) "h",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluez_profile1_interface__new_connection_method_in_args__properties_arg =
{
  -1,  /* ref count */
  (gchar *) "properties",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluez_profile1_interface__new_connection_method_in_args[] =
{
  &org_bluez_profile1_interface__new_connection_method_in_args__device_arg,
  &org_bluez_profile1_interface__new_connection_method_in_args__fd_arg,
  &org_bluez_profile1_interface__new_connection_method_in_args__properties_arg,
  NULL,
};

const GDBusMethodInfo org_bluez_profile1_interface__new_connection_method =
{
  -1,  /* ref count */
  (gchar *) "NewConnection",
  (GDBusArgInfo **) org_bluez_profile1_interface__new_connection_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluez_profile1_interface__request_disconnection_method_in_args__device_arg =
{
  -1,  /* ref count */
  (gchar *) "device",
  (gchar *) "o",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluez_profile1_interface__request_disconnection_method_in_args[] =
{
  &org_bluez_profile1_interface__request_disconnection_method_in_args__device_arg,
  NULL,
};

const GDBusMethodInfo org_bluez_profile1_interface__request_disconnection_method =
{
  -1,  /* ref count */
  (gchar *) "RequestDisconnection",
  (GDBusArgInfo **) org_bluez_profile1_interface__request_disconnection_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo org_bluez_profile1_interface__release_method =
{
  -1,  /* ref count */
  (gchar *) "Release",
  NULL,  /* no in args */
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const org_bluez_profile1_interface_methods[] =
{
  &org_bluez_profile1_interface__new_connection_method,
  &org_bluez_profile1_interface__request_disconnection_method,
  &org_bluez_profile1_interface__release_method,
  NULL,
};

const GDBusInterfaceInfo org_bluez_profile1_interface =
{
  -1,  /* ref count */
  (gchar *) "org.bluez.Profile1",
  (GDBusMethodInfo **) org_bluez_profile1_interface_methods,
  NULL,  /* no signals */
NULL,  /* no properties */
  NULL,  /* no annotations */
};

/*
 * This file is generated by dbus-codegen.py, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#include "bluez-iface.h"
#include <gio/gio.h>
#include <glib-object.h>
#include <glib.h>
#include "dbus.h"

typedef struct {
  GDBusInterfaceSkeletonClass parent;
} OrgBluezMediaEndpoint1SkeletonClass;

G_DEFINE_TYPE(OrgBluezMediaEndpoint1Skeleton, org_bluez_media_endpoint1_skeleton,
  G_TYPE_DBUS_INTERFACE_SKELETON)

static void org_bluez_media_endpoint1_skeleton_class_init(OrgBluezMediaEndpoint1SkeletonClass *ifc) {
    GDBusInterfaceSkeletonClass *ifc_ = G_DBUS_INTERFACE_SKELETON_CLASS(ifc);
    ifc_->get_info = g_dbus_interface_skeleton_ex_class_get_info;
    ifc_->get_vtable = g_dbus_interface_skeleton_ex_class_get_vtable;
    ifc_->get_properties = g_dbus_interface_skeleton_ex_class_get_properties;
}

static void org_bluez_media_endpoint1_skeleton_init(G_GNUC_UNUSED OrgBluezMediaEndpoint1Skeleton *ifs) {
}

/**
 * Create a skeleton for org.bluez.MediaEndpoint1 interface.
 *
 * @return On success, this function returns newly allocated GIO interface
 *   skeleton object, which shall be freed with g_object_unref(). If error
 *   occurs, NULL is returned. */
OrgBluezMediaEndpoint1Skeleton *org_bluez_media_endpoint1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func) {
  const GType type = org_bluez_media_endpoint1_skeleton_get_type();
  return g_dbus_interface_skeleton_ex_new(type,
    (GDBusInterfaceInfo *)&org_bluez_media_endpoint1_interface,
    vtable, userdata, userdata_free_func);
}

typedef struct {
  GDBusInterfaceSkeletonClass parent;
} OrgBluezBatteryProvider1SkeletonClass;

G_DEFINE_TYPE(OrgBluezBatteryProvider1Skeleton, org_bluez_battery_provider1_skeleton,
  G_TYPE_DBUS_INTERFACE_SKELETON)

static void org_bluez_battery_provider1_skeleton_class_init(OrgBluezBatteryProvider1SkeletonClass *ifc) {
    GDBusInterfaceSkeletonClass *ifc_ = G_DBUS_INTERFACE_SKELETON_CLASS(ifc);
    ifc_->get_info = g_dbus_interface_skeleton_ex_class_get_info;
    ifc_->get_vtable = g_dbus_interface_skeleton_ex_class_get_vtable;
    ifc_->get_properties = g_dbus_interface_skeleton_ex_class_get_properties;
}

static void org_bluez_battery_provider1_skeleton_init(G_GNUC_UNUSED OrgBluezBatteryProvider1Skeleton *ifs) {
}

/**
 * Create a skeleton for org.bluez.BatteryProvider1 interface.
 *
 * @return On success, this function returns newly allocated GIO interface
 *   skeleton object, which shall be freed with g_object_unref(). If error
 *   occurs, NULL is returned. */
OrgBluezBatteryProvider1Skeleton *org_bluez_battery_provider1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func) {
  const GType type = org_bluez_battery_provider1_skeleton_get_type();
  return g_dbus_interface_skeleton_ex_new(type,
    (GDBusInterfaceInfo *)&org_bluez_battery_provider1_interface,
    vtable, userdata, userdata_free_func);
}

typedef struct {
  GDBusInterfaceSkeletonClass parent;
} OrgBluezProfile1SkeletonClass;

G_DEFINE_TYPE(OrgBluezProfile1Skeleton, org_bluez_profile1_skeleton,
  G_TYPE_DBUS_INTERFACE_SKELETON)

static void org_bluez_profile1_skeleton_class_init(OrgBluezProfile1SkeletonClass *ifc) {
    GDBusInterfaceSkeletonClass *ifc_ = G_DBUS_INTERFACE_SKELETON_CLASS(ifc);
    ifc_->get_info = g_dbus_interface_skeleton_ex_class_get_info;
    ifc_->get_vtable = g_dbus_interface_skeleton_ex_class_get_vtable;
    ifc_->get_properties = g_dbus_interface_skeleton_ex_class_get_properties;
}

static void org_bluez_profile1_skeleton_init(G_GNUC_UNUSED OrgBluezProfile1Skeleton *ifs) {
}

/**
 * Create a skeleton for org.bluez.Profile1 interface.
 *
 * @return On success, this function returns newly allocated GIO interface
 *   skeleton object, which shall be freed with g_object_unref(). If error
 *   occurs, NULL is returned. */
OrgBluezProfile1Skeleton *org_bluez_profile1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func) {
  const GType type = org_bluez_profile1_skeleton_get_type();
  return g_dbus_interface_skeleton_ex_new(type,
    (GDBusInterfaceInfo *)&org_bluez_profile1_interface,
    vtable, userdata, userdata_free_func);
}
