#include "lang.h"

const lang_t *now_lang;

const lang_t lang_ch = {
    .empty = "",
    .title = "欢迎使用ColorAudio",
    .time_text1 = "/:/",
    .time_text2 = "0:00",
    .main_text1 = "本地音乐",
    .main_text2 = "蓝牙音频",
    .main_text3 = "USB音频",
    .main_text4 = "设置",
    .main_text5 = "是否要同时关闭播放",
    .main_text6 = "正在播放本地音乐",
    .main_text7 = "正在播放本地音乐：%s",
    .main_text8 = "正在读取本地歌曲列表",
    .music_text1 = "无音乐",
    .music_text2 = "无音频",
    .music_text3 = "所有列表",
    .music_text4 = "搜索包含“%s”的结果",
    .music_text5 = "清除搜索结果",
    .music_text6 = "无歌词",
    .music_text7 = "歌词获取失败",
    .music_text8 = "正在获取歌词",
    .music_text9 = "正在扫描音乐",
    .music_text10 = "正在等待USB连接",
    .music_text11 = "正在播放USB音频",
    .music_text12 = "搜索内容",
    .dialog_text1 = "取消",
    .dialog_text2 = "确认",
    .dialog_text3 = "关闭",
    .bt_text1 = "启用配对",
    .bt_text2 = "已连接：%s",
    .bt_text3 = "未连接设备",
    .bt_text4 = "设备请求配对，配对码：%d",
    .usb_text1 = "设置USB音频模式",
    .usb_text2 = "启用USB音频",
    .usb_text3 = "设备模式：",
    .usb_text4 = "采样率：",
    .usb_text5 = "比特位：",
    .usb_text6 = "未连接",
    .usb_text7 = "采样率：%d 位宽：%d 音量：-%.1fdB",
    .usb_text8 = "正在开启USB音频",
    .usb_text9 = "正在关闭USB音频",
    .setting_text1 = "无线网络",
    .setting_text2 = "无线模块电源",
    .setting_text3 = "WIFI",
    .setting_text4 = "未连接网络",
    .setting_text5 = "可用网络列表",
    .setting_text6 = "扫描无线网络",
    .setting_text7 = "正在开启无线模块电源",
    .setting_text8 = "正在关闭无线模块电源",
    .setting_text9 = "正在开启WIFI",
    .setting_text10 = "正在关闭WIFI",
    .setting_text11 = "找不到WIFI设备",
    .setting_text12 = "WIFI设备未就绪",
    .setting_text13 = "无法扫描无线网络",
    .setting_text14 = "输入WIFI密码",
    .setting_text15 = "WIFI连接失败",
    .setting_text16 = "断开连接",
    .setting_text17 = "已连接网络：%s",
    .setting_text18 = "未知的WIFI状态",
    .setting_text19 = "WIFI操作失败",
};

void lang_init()
{
    now_lang = &lang_ch;
}