/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __ORG_BLUEZ_H__
#define __ORG_BLUEZ_H__

#include <gio/gio.h>

G_BEGIN_DECLS

extern  const GDBusInterfaceInfo org_bluez_media_endpoint1_interface;
extern  const GDBusInterfaceInfo org_bluez_battery_provider1_interface;
extern  const GDBusInterfaceInfo org_bluez_profile1_interface;

G_END_DECLS

#endif /* __ORG_BLUEZ_H__ */
/*
 * This file is generated by dbus-codegen.py, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#pragma once
#ifndef _ORG_BLUEZ_H_
#define _ORG_BLUEZ_H_

#include <gio/gio.h>
#include <glib.h>
#include "dbus.h"

typedef struct {
  GDBusInterfaceSkeletonEx parent;
} OrgBluezMediaEndpoint1Skeleton;

OrgBluezMediaEndpoint1Skeleton *org_bluez_media_endpoint1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC(OrgBluezMediaEndpoint1Skeleton, g_object_unref)
#endif

typedef struct {
  GDBusInterfaceSkeletonEx parent;
} OrgBluezBatteryProvider1Skeleton;

OrgBluezBatteryProvider1Skeleton *org_bluez_battery_provider1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC(OrgBluezBatteryProvider1Skeleton, g_object_unref)
#endif

typedef struct {
  GDBusInterfaceSkeletonEx parent;
} OrgBluezProfile1Skeleton;

OrgBluezProfile1Skeleton *org_bluez_profile1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC(OrgBluezProfile1Skeleton, g_object_unref)
#endif
#endif