/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __ORG_BLUEALSA_H__
#define __ORG_BLUEALSA_H__

#include <gio/gio.h>

G_BEGIN_DECLS

extern  const GDBusInterfaceInfo org_bluealsa_pcm1_interface;
extern  const GDBusInterfaceInfo org_bluealsa_rfcomm1_interface;
extern  const GDBusInterfaceInfo org_bluealsa_manager1_interface;

G_END_DECLS

#endif /* __ORG_BLUEALSA_H__ */
/*
 * This file is generated by dbus-codegen.py, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#pragma once
#ifndef _ORG_BLUEALSA_H_
#define _ORG_BLUEALSA_H_

#include <gio/gio.h>
#include <glib.h>
#include "dbus.h"

typedef struct {
  GDBusInterfaceSkeletonEx parent;
} OrgBluealsaPcm1Skeleton;

OrgBluealsaPcm1Skeleton *org_bluealsa_pcm1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC(OrgBluealsaPcm1Skeleton, g_object_unref)
#endif

typedef struct {
  GDBusInterfaceSkeletonEx parent;
} OrgBluealsaRfcomm1Skeleton;

OrgBluealsaRfcomm1Skeleton *org_bluealsa_rfcomm1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC(OrgBluealsaRfcomm1Skeleton, g_object_unref)
#endif

typedef struct {
  GDBusInterfaceSkeletonEx parent;
} OrgBluealsaManager1Skeleton;

OrgBluealsaManager1Skeleton *org_bluealsa_manager1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC(OrgBluealsaManager1Skeleton, g_object_unref)
#endif
#endif