/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "org.bluealsa.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.bluealsa.PCM1 */

const GDBusArgInfo org_bluealsa_pcm1_interface__open_method_out_args__fd_pcm_arg =
{
  -1,  /* ref count */
  (gchar *) "fd_pcm",
  (gchar *) "h",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluealsa_pcm1_interface__open_method_out_args__fd_ctrl_arg =
{
  -1,  /* ref count */
  (gchar *) "fd_ctrl",
  (gchar *) "h",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluealsa_pcm1_interface__open_method_out_args[] =
{
  &org_bluealsa_pcm1_interface__open_method_out_args__fd_pcm_arg,
  &org_bluealsa_pcm1_interface__open_method_out_args__fd_ctrl_arg,
  NULL,
};

const GDBusMethodInfo org_bluealsa_pcm1_interface__open_method =
{
  -1,  /* ref count */
  (gchar *) "Open",
  NULL,  /* no in args */
  (GDBusArgInfo **) org_bluealsa_pcm1_interface__open_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluealsa_pcm1_interface__get_codecs_method_out_args__codecs_arg =
{
  -1,  /* ref count */
  (gchar *) "codecs",
  (gchar *) "a{sa{sv}}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluealsa_pcm1_interface__get_codecs_method_out_args[] =
{
  &org_bluealsa_pcm1_interface__get_codecs_method_out_args__codecs_arg,
  NULL,
};

const GDBusMethodInfo org_bluealsa_pcm1_interface__get_codecs_method =
{
  -1,  /* ref count */
  (gchar *) "GetCodecs",
  NULL,  /* no in args */
  (GDBusArgInfo **) org_bluealsa_pcm1_interface__get_codecs_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluealsa_pcm1_interface__select_codec_method_in_args__codec_arg =
{
  -1,  /* ref count */
  (gchar *) "codec",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_bluealsa_pcm1_interface__select_codec_method_in_args__props_arg =
{
  -1,  /* ref count */
  (gchar *) "props",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluealsa_pcm1_interface__select_codec_method_in_args[] =
{
  &org_bluealsa_pcm1_interface__select_codec_method_in_args__codec_arg,
  &org_bluealsa_pcm1_interface__select_codec_method_in_args__props_arg,
  NULL,
};

const GDBusMethodInfo org_bluealsa_pcm1_interface__select_codec_method =
{
  -1,  /* ref count */
  (gchar *) "SelectCodec",
  (GDBusArgInfo **) org_bluealsa_pcm1_interface__select_codec_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const org_bluealsa_pcm1_interface_methods[] =
{
  &org_bluealsa_pcm1_interface__open_method,
  &org_bluealsa_pcm1_interface__get_codecs_method,
  &org_bluealsa_pcm1_interface__select_codec_method,
  NULL,
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__device_property =
{
  -1,  /* ref count */
  (gchar *) "Device",
  (gchar *) "o",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__sequence_property =
{
  -1,  /* ref count */
  (gchar *) "Sequence",
  (gchar *) "u",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__transport_property =
{
  -1,  /* ref count */
  (gchar *) "Transport",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__mode_property =
{
  -1,  /* ref count */
  (gchar *) "Mode",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__running_property =
{
  -1,  /* ref count */
  (gchar *) "Running",
  (gchar *) "b",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__format_property =
{
  -1,  /* ref count */
  (gchar *) "Format",
  (gchar *) "q",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__channels_property =
{
  -1,  /* ref count */
  (gchar *) "Channels",
  (gchar *) "y",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__channel_map_property =
{
  -1,  /* ref count */
  (gchar *) "ChannelMap",
  (gchar *) "as",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__rate_property =
{
  -1,  /* ref count */
  (gchar *) "Rate",
  (gchar *) "u",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__codec_property =
{
  -1,  /* ref count */
  (gchar *) "Codec",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__codec_configuration_property =
{
  -1,  /* ref count */
  (gchar *) "CodecConfiguration",
  (gchar *) "ay",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__delay_property =
{
  -1,  /* ref count */
  (gchar *) "Delay",
  (gchar *) "q",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__client_delay_property =
{
  -1,  /* ref count */
  (gchar *) "ClientDelay",
  (gchar *) "n",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__soft_volume_property =
{
  -1,  /* ref count */
  (gchar *) "SoftVolume",
  (gchar *) "b",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_pcm1_interface__volume_property =
{
  -1,  /* ref count */
  (gchar *) "Volume",
  (gchar *) "ay",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const org_bluealsa_pcm1_interface_properties[] =
{
  &org_bluealsa_pcm1_interface__device_property,
  &org_bluealsa_pcm1_interface__sequence_property,
  &org_bluealsa_pcm1_interface__transport_property,
  &org_bluealsa_pcm1_interface__mode_property,
  &org_bluealsa_pcm1_interface__running_property,
  &org_bluealsa_pcm1_interface__format_property,
  &org_bluealsa_pcm1_interface__channels_property,
  &org_bluealsa_pcm1_interface__channel_map_property,
  &org_bluealsa_pcm1_interface__rate_property,
  &org_bluealsa_pcm1_interface__codec_property,
  &org_bluealsa_pcm1_interface__codec_configuration_property,
  &org_bluealsa_pcm1_interface__delay_property,
  &org_bluealsa_pcm1_interface__client_delay_property,
  &org_bluealsa_pcm1_interface__soft_volume_property,
  &org_bluealsa_pcm1_interface__volume_property,
  NULL,
};

const GDBusInterfaceInfo org_bluealsa_pcm1_interface =
{
  -1,  /* ref count */
  (gchar *) "org.bluealsa.PCM1",
  (GDBusMethodInfo **) org_bluealsa_pcm1_interface_methods,
  NULL,  /* no signals */
  (GDBusPropertyInfo **) org_bluealsa_pcm1_interface_properties,
  NULL,  /* no annotations */
};

/* ------------------------------------------------------------------------ */
/* Definitions for org.bluealsa.RFCOMM1 */

const GDBusArgInfo org_bluealsa_rfcomm1_interface__open_method_out_args__fd_arg =
{
  -1,  /* ref count */
  (gchar *) "fd",
  (gchar *) "h",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_bluealsa_rfcomm1_interface__open_method_out_args[] =
{
  &org_bluealsa_rfcomm1_interface__open_method_out_args__fd_arg,
  NULL,
};

const GDBusMethodInfo org_bluealsa_rfcomm1_interface__open_method =
{
  -1,  /* ref count */
  (gchar *) "Open",
  NULL,  /* no in args */
  (GDBusArgInfo **) org_bluealsa_rfcomm1_interface__open_method_out_args,
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const org_bluealsa_rfcomm1_interface_methods[] =
{
  &org_bluealsa_rfcomm1_interface__open_method,
  NULL,
};

const GDBusPropertyInfo org_bluealsa_rfcomm1_interface__transport_property =
{
  -1,  /* ref count */
  (gchar *) "Transport",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_rfcomm1_interface__features_property =
{
  -1,  /* ref count */
  (gchar *) "Features",
  (gchar *) "as",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_rfcomm1_interface__battery_property =
{
  -1,  /* ref count */
  (gchar *) "Battery",
  (gchar *) "y",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const org_bluealsa_rfcomm1_interface_properties[] =
{
  &org_bluealsa_rfcomm1_interface__transport_property,
  &org_bluealsa_rfcomm1_interface__features_property,
  &org_bluealsa_rfcomm1_interface__battery_property,
  NULL,
};

const GDBusInterfaceInfo org_bluealsa_rfcomm1_interface =
{
  -1,  /* ref count */
  (gchar *) "org.bluealsa.RFCOMM1",
  (GDBusMethodInfo **) org_bluealsa_rfcomm1_interface_methods,
  NULL,  /* no signals */
  (GDBusPropertyInfo **) org_bluealsa_rfcomm1_interface_properties,
  NULL,  /* no annotations */
};

/* ------------------------------------------------------------------------ */
/* Definitions for org.bluealsa.Manager1 */

const GDBusPropertyInfo org_bluealsa_manager1_interface__version_property =
{
  -1,  /* ref count */
  (gchar *) "Version",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_manager1_interface__adapters_property =
{
  -1,  /* ref count */
  (gchar *) "Adapters",
  (gchar *) "as",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_manager1_interface__profiles_property =
{
  -1,  /* ref count */
  (gchar *) "Profiles",
  (gchar *) "as",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_bluealsa_manager1_interface__codecs_property =
{
  -1,  /* ref count */
  (gchar *) "Codecs",
  (gchar *) "as",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const org_bluealsa_manager1_interface_properties[] =
{
  &org_bluealsa_manager1_interface__version_property,
  &org_bluealsa_manager1_interface__adapters_property,
  &org_bluealsa_manager1_interface__profiles_property,
  &org_bluealsa_manager1_interface__codecs_property,
  NULL,
};

const GDBusInterfaceInfo org_bluealsa_manager1_interface =
{
  -1,  /* ref count */
  (gchar *) "org.bluealsa.Manager1",
  NULL,  /* no methods */
  NULL,  /* no signals */
  (GDBusPropertyInfo **) org_bluealsa_manager1_interface_properties,
  NULL,  /* no annotations */
};

/*
 * This file is generated by dbus-codegen.py, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#include "org.bluealsa.h"
#include <gio/gio.h>
#include <glib-object.h>
#include <glib.h>
#include "dbus.h"

typedef struct {
  GDBusInterfaceSkeletonClass parent;
} OrgBluealsaPcm1SkeletonClass;

G_DEFINE_TYPE(OrgBluealsaPcm1Skeleton, org_bluealsa_pcm1_skeleton,
  G_TYPE_DBUS_INTERFACE_SKELETON)

static void org_bluealsa_pcm1_skeleton_class_init(OrgBluealsaPcm1SkeletonClass *ifc) {
    GDBusInterfaceSkeletonClass *ifc_ = G_DBUS_INTERFACE_SKELETON_CLASS(ifc);
    ifc_->get_info = g_dbus_interface_skeleton_ex_class_get_info;
    ifc_->get_vtable = g_dbus_interface_skeleton_ex_class_get_vtable;
    ifc_->get_properties = g_dbus_interface_skeleton_ex_class_get_properties;
}

static void org_bluealsa_pcm1_skeleton_init(G_GNUC_UNUSED OrgBluealsaPcm1Skeleton *ifs) {
}

/**
 * Create a skeleton for org.bluealsa.PCM1 interface.
 *
 * @return On success, this function returns newly allocated GIO interface
 *   skeleton object, which shall be freed with g_object_unref(). If error
 *   occurs, NULL is returned. */
OrgBluealsaPcm1Skeleton *org_bluealsa_pcm1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func) {
  const GType type = org_bluealsa_pcm1_skeleton_get_type();
  return g_dbus_interface_skeleton_ex_new(type,
    (GDBusInterfaceInfo *)&org_bluealsa_pcm1_interface,
    vtable, userdata, userdata_free_func);
}

typedef struct {
  GDBusInterfaceSkeletonClass parent;
} OrgBluealsaRfcomm1SkeletonClass;

G_DEFINE_TYPE(OrgBluealsaRfcomm1Skeleton, org_bluealsa_rfcomm1_skeleton,
  G_TYPE_DBUS_INTERFACE_SKELETON)

static void org_bluealsa_rfcomm1_skeleton_class_init(OrgBluealsaRfcomm1SkeletonClass *ifc) {
    GDBusInterfaceSkeletonClass *ifc_ = G_DBUS_INTERFACE_SKELETON_CLASS(ifc);
    ifc_->get_info = g_dbus_interface_skeleton_ex_class_get_info;
    ifc_->get_vtable = g_dbus_interface_skeleton_ex_class_get_vtable;
    ifc_->get_properties = g_dbus_interface_skeleton_ex_class_get_properties;
}

static void org_bluealsa_rfcomm1_skeleton_init(G_GNUC_UNUSED OrgBluealsaRfcomm1Skeleton *ifs) {
}

/**
 * Create a skeleton for org.bluealsa.RFCOMM1 interface.
 *
 * @return On success, this function returns newly allocated GIO interface
 *   skeleton object, which shall be freed with g_object_unref(). If error
 *   occurs, NULL is returned. */
OrgBluealsaRfcomm1Skeleton *org_bluealsa_rfcomm1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func) {
  const GType type = org_bluealsa_rfcomm1_skeleton_get_type();
  return g_dbus_interface_skeleton_ex_new(type,
    (GDBusInterfaceInfo *)&org_bluealsa_rfcomm1_interface,
    vtable, userdata, userdata_free_func);
}

typedef struct {
  GDBusInterfaceSkeletonClass parent;
} OrgBluealsaManager1SkeletonClass;

G_DEFINE_TYPE(OrgBluealsaManager1Skeleton, org_bluealsa_manager1_skeleton,
  G_TYPE_DBUS_INTERFACE_SKELETON)

static void org_bluealsa_manager1_skeleton_class_init(OrgBluealsaManager1SkeletonClass *ifc) {
    GDBusInterfaceSkeletonClass *ifc_ = G_DBUS_INTERFACE_SKELETON_CLASS(ifc);
    ifc_->get_info = g_dbus_interface_skeleton_ex_class_get_info;
    ifc_->get_vtable = g_dbus_interface_skeleton_ex_class_get_vtable;
    ifc_->get_properties = g_dbus_interface_skeleton_ex_class_get_properties;
}

static void org_bluealsa_manager1_skeleton_init(G_GNUC_UNUSED OrgBluealsaManager1Skeleton *ifs) {
}

/**
 * Create a skeleton for org.bluealsa.Manager1 interface.
 *
 * @return On success, this function returns newly allocated GIO interface
 *   skeleton object, which shall be freed with g_object_unref(). If error
 *   occurs, NULL is returned. */
OrgBluealsaManager1Skeleton *org_bluealsa_manager1_skeleton_new(
    const GDBusInterfaceSkeletonVTable *vtable,
    void *userdata,
    GDestroyNotify userdata_free_func) {
  const GType type = org_bluealsa_manager1_skeleton_get_type();
  return g_dbus_interface_skeleton_ex_new(type,
    (GDBusInterfaceInfo *)&org_bluealsa_manager1_interface,
    vtable, userdata, userdata_free_func);
}
